### ISSUE TITLE
Add a setting to announce loot regardless of master looter role

### ISSUE THREAD

**Issue by BjarkeM** [papa-smurf/Gargul#18]
Quite a few raids run with group loot, where everyone except "the master looter" passes on loot automatically, since it's faster than having a single person running around grabbing loot.

It would be nice to be able to toggle off the master looter requirement for announcing loot.

**Comment by papa-smurf** [comment]
Not as simple as you might think sadly. Gargul currently announces what's on a corpse, so in order for this to work properly everyone in the raid would need Gargul with this setting enabled because you never know who actually loots the corpse. That also means that if two people loot the corpse, two people will announce the loot. Or 3.. 4 .. 5? You get the picture :)

Is this surmountable? Yes, but a simple setting would not be the solution sadly.
