### ISSUE TITLE
Request for Auto Distribution of SR List on Loot

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#21]
Another issue that came in from some of my old users, it would be nice to have the ability to automatically loot things to people on the SR list as you were running.

I get why you'd want to turn this off, if you want to make sure someone completes a run, but often times it's just nice to get rid of shit before they clutter your bags.

Creates an issue though... some items only have one person who SR'd them... easy to distribute. Others have multiple reserves... having to do loot differently, some mid-run, and some at the end can be a bit of a pain. 

Meh, this one is not a great feature to port over I guess... I hate stopping for loot mid-run. 

And it's a good opportunity to give people a win / happy experience. And tag some branding in while you do it.

Messages would have to be like...

/raid Gargul automatically awarded [Some Purple] to Joe based on SoftRes.it List!

or 

/raid Gargul saw that [Some Purple] Reserved by Joe and Sally based on SoftRest.it List. Master Looter will handle this manually.

Meh. Never been wild about the UX there, but I do like automation when you can.

**Comment by papa-smurf** [comment]
Agreed and it's already on the todo list. I personally never stop for loot and do everyting at the end. Loot distribution, no matter how automated, is distracting and always results in players paying less attention to the raid itself. You also run a real risk of pugs bailing, it's sad, but it happens. I can not recommend doing loot during a run. Some people swear by it, which is why auto-assigning loot on single SRs is on the list :)

**Comment by Gogo1951** [comment]
Does it have a tooltip when something is not SoftReserved, or just when it is? Can you include it for both? Helps with loot. I didn't see anything and I just kept checking the website. 

(We had a guy put his name in wrong, it's be good to have misspellings included in the tooltips in case the auto-match doesn't work... or someone drops on one toon and comes in on another. This happens a lot on Gruul's... bring a geared mage to tank an a scrub rogue for the DST roll.)

**Comment by papa-smurf** [comment]
Misspellings is something you can enable in the settings (uncheck the in-raid setting). Not enabled by default because a lot of soft-reserves often come from people who aren't even in the raid.

Since you can have softres/tmb and other data loaded simultaneously it would be a bit too much to state for each source when no data is available. If you don't see names then no-one reserved it basically.

If nothing showed on your tooltips at all then the data wasn't imported or the players need a lot of help spelling their own names 😂
