### ISSUE TITLE
Suggest Announce on SoftRes.it Import

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#27]
ML gets a message, but for transparency the raid should get one too.

**Comment by Gogo1951** [comment]
Really love the "SoftRes Missing" announce. That's great! 

When you import the list, it'd be nice to say like "37 Soft Reserves for 23 Items by 9 Players. 3 Soft Reserves by Players not in Raid. Missing Soft Reserves from X, Y, Z." Like that's be really cool to have all that in one message. Makes for really quick / sane check on the import.

Also... may be nice to send a tell to every one saying like, "I have you down for [Purple Item], let the raid leader know if that's not accurate." Always better to over-communicate in PUGs.

**Comment by papa-smurf** [comment]
I like the on-import messaging to the ML to allow for a quick check. Not a fan of spamming raiders, especially since you tend to import SRs multiple times (to see if everyone reserved).

I could implement it with an additional checksum check or something to make sure players never get the same message more than once.

Good idea
