### ISSUE TITLE
Broad Impressions

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#33]
Hey @papa-smurf ,

I just ran a raid with Gargul. Opened a bunch of tickets around some thoughts and ideas.

The stuff that really stood out...

#20 Trade announce is key for transparency during GDKPs / PUGs. There should always be an announce when trading / awarding gear.

#32 / #21 Ideally the add-on could automate a bit more of the looting.

#30 This was annoying when I changed characters. Having to re-type a name... eww. That's super cringe UX. Should always be a drop down of people in the current raid.

#31 / #29 This was just annoying. Needs better conflict announcements.

Past that, I sent over a few suggestions for features. I think add-ons like this are good for Master Looters, but you'd increase users if you had a few features for non-MLs too. 

#22 / #25 / #28 All suggestions around future features. Feel free to take code where you can from any of my projects.

On the whole worked exactly as expected. 

Few more settings to dive into than I think are needed... felt a little "dev-y" at times. But mostly worked as expected.

Less is more, idiot proof the UX and people will thank you. Ha.

Glad you're into this! Feel free to take suggestions or not. It's your addon. (=

I think GDKPs and PUGs are really important, and having an addon that would handle loot there was my goal with GogoLoot. I think having a GDKPd feature would cement Gargul in as "the loot add-on" and I think it'd be pretty great if you could add something like that too.

Anyway nice work! Keep it up!

**Comment by papa-smurf** [comment]
#20: Gargul is not designed with GDKPs in mind (yet). That will change in the near future, but in it's current form I fully disagree that it should be in there. It's a nice to have that's for sure though.

#32: Not automation-related, mostly textual feedback. As mentioned I agree, but a lot of effort for little value in the current setup

#21: Agreed and it's already on the todo list. I personally never stop for loot and do everyting at the end. Loot distribution, no matter how automated, is distracting and always results in players paying less attention to the raid itself. You also run a real risk of pugs bailing, it's sad, but it happens. I can not recommend doing loot during a run. Some people swear by it, which is why auto-assigning loot on single SRs is on the list :)

#30: Relax :) Use `SELF` instead of your char name for starters

#31: Need more info, don't know what this means

#29: See issue, can't reproduce

#22 / #25 are added to the todo list, need more info on #28
