### ISSUE TITLE
Changes to +1 Increments

### ISSUE THREAD

**Issue by Nagello** [papa-smurf/Gargul#37]
We use a spreadsheet and a form to add increments to players rolls on one item they reserve for each week that they haven't received the item.  I was wondering if there was a way to use the data and add the amount that they have additional to that specific item.

![image](https://user-images.githubusercontent.com/71985495/163301077-eab97448-712c-4594-93e6-5f0b908dde11.png)

This is very niche and might not be worth investigating but can we add a way to add +10, & +100 instead of just +1 and clicking an additional arrow or being able to type in the value.

![image](https://user-images.githubusercontent.com/71985495/163300770-ea912fa1-62ac-4567-9f2c-60b52e26bc36.png)

**Comment by papa-smurf** [comment]
PlusOnes are not suitable for this, since they are meant for a character not an item :) Boosted rolls is something that will be released very soon, but those values are also on a per-character basis and not per item, though I imagine it would still help a lot in your case.

A boosted roll would result in the user rolling 40-140 for example, and in case of an incoming boosted roll you could always check whether they're allowed to use that roll on the item you're currently rolling out

**Comment by papa-smurf** [comment]
Any chance you can share the sheet you use by the way? Could also DM me on discord (Zh0rax#1454)
