### ISSUE TITLE
Request to make Loot Announce Display Mob Names

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#38]
![image](https://user-images.githubusercontent.com/55365231/163698548-56bd6641-3775-48e0-8bcb-651e4e77b190.png)

We'll get something drop, but I haven't got a clue where it is.

Would be nice if ANYONE who had Gargul installed could trigger a message to the Master Looter (or whoever does the announce) that trips the announce.

So like anyone who loots, makes the lead say, "Hey there's this thing on this dead mob." 

But really just say the name to help me sort out where something is would be a huge help.

/raid {rt3} Gargul : [Item X] on Mob Name.

**Comment by Gogo1951** [comment]
Oh, also... can't tell if it's just someone else using a different version, but there's a mix of...

<Gargul> 

{rt3} Gargul : 

Going on. Good to standardize.

**Comment by papa-smurf** [comment]
If you can tell where items are in a pile of mobs in Mount Hyjal or the patron rooms in BT based on a mob's name, then I have to commend you on your skills 😂 I'd say it's so circumstantially useful that I can imagine it being more of a nuisance than of any help.

As for loot announcing: I want to keep that to the master looter. Why? Because even if players have the add-on they don't necessarily have the (correct!) softres or tmb data.

Doing this properly would be too much work for my taste, especially since the master looter needs to go there anyways to pick up the items.

- See if anyone with the add-on already announced the items
- Checking if they included all the info for all the items
- And if they announced it but didn't include all the data, I will have to announce it once more

I'd rather focus on other features for now at least.

The <> {rt3} will be fixed in today's update!

**Comment by Gogo1951** [comment]
Makes sense. (=
