### ISSUE TITLE
enhancement : Support Reversed roll

### ISSUE THREAD

**Issue by QuentinNIO** [papa-smurf/Gargul#55]
Gargul does support reversed roll by tricking range, but it still keep reserved items or other stuff on top of the list of rolls.

**Comment by papa-smurf** [comment]
This does not sound like a bug to me, but perhaps I'm not fully understanding the situation. Feel free to drop by on our discord!

https://discord.gg/sqvNKNCA

**Comment by QuentinNIO** [comment]
did we need to go to discord to ask for a new feature or enhancement ? 

it depend how we consider feature that allow us to edit every roll's button and award any item to the lowest roll instead of the highest. Currently SoftRes items are always shown on top we do not have the hability to put them bellow instead or even link them to a priority level (this would be amazing)


your tool is amazing and really a time saver, thanks for all and if i'm at the wrong place to ask enhancement feel free to close this issue :) 

regards

**Comment by papa-smurf** [comment]
@QuentinNIO I was in the process of closing the Gargul issue board and move everything to discord, but no you were not in the wrong place!

I acknowledge your use-case, but deem it too circumstantial to warant an extra setting or the effort it requires. If more people have a use for it at some point, then maybe :)

For now you could click the table header in order to invert the sorting on the rolls:

![image](https://user-images.githubusercontent.com/4224975/188919340-14efc6d1-2b1a-4c37-9469-7e15ea8a4003.png)
