### ISSUE TITLE
Exporter window should be non-editable

### ISSUE THREAD

**Issue by kdim953** [papa-smurf/Gargul#59]
The exporter window lets you add/remove text, but does not save. It would be preferred if the exporter window was not editable as to not cause confusion when dealing with an item that has been assigned, but then shortly after re-assigned to a different raider.

![Untitled](https://user-images.githubusercontent.com/19291898/195697292-fa067353-5783-41d4-ba4c-f0d820689442.png)

**Comment by papa-smurf** [comment]
Allowing input is necessary in order to be able to ctrl+a and ctrl+c. It can be done, but has multiple potential drawbacks especially on larger exports so I chose not to implement them.

It's an export, the name says it all hopefully: it's meant to export data, not import/change it.

I get the confusion however, so what I could do is show some info there.

**Comment by papa-smurf** [comment]
This took my way too long to implement, my apologies!

![image](https://user-images.githubusercontent.com/4224975/208538534-51073142-2954-4b78-ba28-e59aae896a8e.png)
