### ISSUE TITLE
Soft reserves not showing in /rw

### ISSUE THREAD

**Issue by magga92** [papa-smurf/Gargul#66]
Imported soft reserves is not showing in /rw when linking an item for roll. It is only showed in /ra so no one really pays attention to it since all is follwing raid warnings. The thing that people see is the message in /ra which says "MS  ROLL 100 and OS ROLL 99", and everyone ignores the "reserved by" which is said in /ra.

**Comment by papa-smurf** [comment]
This is a feature. The size of chat messages is limited in WoW and showing multiple /rw messages in quick succession does not work as well as you'd like it to.

People ignoring the message in /ra should be their problem, not yours, since the roll window still sorts the person who actually has it soft-reserved on top.

A much better way to get people to notice who SR-ed something is to have them install Gargul or at least ask them to. That way they see it on the tooltip whenever they're about to roll on something :)
